// Pack a mined / merged motif library (tools/mine_motifs.mjs, tools/merge_motifs.mjs output) into the text module the engine
// ships: one motif per line, `<canonical key>\t<n>\t<models>`. The key already encodes every part, so the JSON's `parts` array
// is dropped (8.1 MB -> 0.9 MB for the 20k-motif merged library), and motifs no setting can reach are left out:
//   - n < minN or models < minModels (the engine's gates are 3 / 2 and only ever rise),
//   - more than maxParts pieces (motifMaxParts is 12 by default; the schema stops well below 16),
//   - a part the catalogue does not have (motifVariants drops those outright).
// usage: node tools/pack_motifs.mjs [in=src/motifs/motifs.json] [--out src/motifs/motifs.js] [--min 3] [--models 2] [--maxParts 16] [--all]
import fs from 'node:fs';
import path from 'node:path';
import { FULL_CATALOG } from '../src/brickgen/pipeline.js';

const arg = (k, d) => { const i = process.argv.indexOf('--' + k); return i > 0 ? process.argv[i + 1] : d; };
export function packMotifs(list, { minN = 3, minModels = 2, maxParts = 16, cat = FULL_CATALOG, note = '' } = {}) {
  const by = new Set(cat.map((c) => c.id));
  for (const [a, b] of Object.entries({ '4287a': '4287', '3747a': '3747' })) if (!by.has(a) && by.has(b)) by.add(a);
  const keep = list.filter((m) => m.n >= minN && m.models >= minModels && m.parts.length <= maxParts && m.parts.every((p) => by.has(p.id)));
  const lines = keep.map((m) => `${m.key}\t${m.n}\t${m.models}`).join('\n');
  const head = `// generated by tools/pack_motifs.mjs${note ? ' from ' + note : ''}: ${keep.length} of ${list.length} motifs (n >= ${minN}, ${minModels}+ models, <= ${maxParts} parts, all parts in the catalogue); do not hand-edit\n`
    + '// one motif per line: `w,d,h|id:rot:i,j,b id:o<ori>:i,j,b ...` then a tab, its count, a tab, the number of models it was\n'
    + '// seen in. Offsets are tenths of a stud (i, j) and half plates (b). motifs/library.js parses it on first use.\n';
  return { text: head + 'export default `' + lines + '`;\n', kept: keep.length, lines };
}
if (import.meta.url === `file://${process.argv[1]}`) {
  const inFile = process.argv.slice(2).find((a) => !a.startsWith('--') && /\.json$/.test(a)) || 'src/motifs/motifs.json';
  const out = arg('out', path.join(path.dirname(inFile), 'motifs.js'));
  const j = JSON.parse(fs.readFileSync(inFile, 'utf8')), list = j.motifs || j;
  const all = process.argv.includes('--all');
  const r = packMotifs(list, { minN: all ? 1 : +arg('min', 3), minModels: all ? 1 : +arg('models', 2), maxParts: all ? 1e9 : +arg('maxParts', 16), note: path.basename(inFile) });
  fs.writeFileSync(out, r.text);
  console.log(`${r.kept} of ${list.length} motifs -> ${out} (${(r.text.length / 1e6).toFixed(2)} MB, was ${(fs.statSync(inFile).size / 1e6).toFixed(2)} MB as JSON)`);
}
