// Pack the generated part catalogues into the text modules the engine ships (see src/brickgen/catalog_pack.js): the height
// fields as run-length text, the triangle geometry into its own module that only export.js imports.
// usage: node tools/pack_catalog.mjs [--out src/brickgen] [--from src/brickgen]   (reads the current modules, writes packed ones)
import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

const arg = (k, d) => { const i = process.argv.indexOf('--' + k); return i > 0 ? process.argv[i + 1] : d; };
const from = arg('from', 'src/brickgen'), out = arg('out', 'src/brickgen');
const G = 5;
const BIG = new Set(['top', 'bot', 'cover', 'tris']);

const rle = (vals, div) => {
  const parts = []; let prev = null, n = 0;
  for (const v of vals) { const q = Math.round(v * div); if (q === prev) n++; else { if (prev !== null) parts.push(n > 1 ? prev + '*' + n : String(prev)); prev = q; n = 1; } }
  if (prev !== null) parts.push(n > 1 ? prev + '*' + n : String(prev));
  return parts.join(',');
};
const flat2 = (rows) => rows.flat();                                   // top / bot: [z][x]
const flat3 = (lv) => lv.flatMap((l) => l.flat());                     // cover: [l][z][x]

export function packCatalog(parts) {
  const lines = parts.map((p) => {
    const small = {}; for (const [k, v] of Object.entries(p)) if (!BIG.has(k)) small[k] = v;
    const nx = p.w * G, nz = p.d * G;
    const top = p.top ? rle(flat2(p.top), 100) : '', bot = p.bot ? rle(flat2(p.bot), 100) : '';
    const cover = p.cover ? rle(flat3(p.cover), 1000) : '', ch = p.cover ? p.cover.length : '';
    if (p.top && p.top.length * p.top[0].length !== nz * nx) throw new Error(`${p.id}: top is ${p.top.length}x${p.top[0].length}, expected ${nz}x${nx}`);
    return [JSON.stringify(small), top, bot, ch, cover].join('\t');
  });
  return lines.join('\n');
}
/**
 * id -> flat triangle coordinates (9 per triangle), as text: tenths of an LDU as integers (0.04 mm, far below what a
 * rendered brick shows, and a third of the characters of the raw floats).
 */
export function packTris(parts) {
  return parts.filter((p) => p.tris && p.tris.length)
    .map((p) => p.id + '\t' + p.tris.flatMap((t) => t.flat()).map((v) => Math.round(v * 10)).join(',')).join('\n');
}

/** escape a packed text for a JS template literal (a part's `missing` list can hold a Windows LDraw path with a backslash) */
const esc = (t) => t.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

const head = (file, n, extra = '') => `// generated by tools/pack_catalog.mjs from ${file} (${n} parts${extra}); do not hand-edit.\n`
  + `// One part per line: small fields as JSON, then the height fields run-length encoded (src/brickgen/catalog_pack.js).\n`;

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  const files = [['catalog.js', 'CATALOG'], ['catalog_ext.js', 'EXT'], ['catalog_shapes.js', 'SHAPES']];
  const all = []; let tris = [];
  for (const [f] of files) {
    const mod = await import(pathToFileURL(path.resolve(from, f)).href);
    const parts = mod.default || mod.CATALOG;
    const was = fs.statSync(path.resolve(from, f)).size;
    const text = packCatalog(parts);
    const js = head(f, parts.length) + `import { unpackCatalog } from './catalog_pack.js';\nexport default unpackCatalog(\`${esc(text)}\`);\n`;
    fs.writeFileSync(path.resolve(out, f), js);
    console.log(`${f}: ${(was / 1e6).toFixed(2)} MB -> ${(js.length / 1e6).toFixed(3)} MB (${parts.length} parts)`);
    all.push(...parts); tris.push(...parts.filter((p) => p.tris && p.tris.length));
  }
  const tt = packTris(tris);
  fs.writeFileSync(path.resolve(out, 'catalog_tris.js'),
    `// generated by tools/pack_catalog.mjs: the drawing geometry of ${tris.length} measured parts, flat triangle coordinates\n`
    + `// (9 per triangle). Only export.js imports this, so a solver worker never loads it. do not hand-edit.\n`
    + `export default \`${esc(tt)}\`;\n`);
  console.log(`catalog_tris.js: ${(tt.length / 1e6).toFixed(2)} MB (${tris.length} parts with geometry)`);
}
