// Every parameter of the method, grouped for the settings panels. Keys match brickgen/constants.js DEFAULTS.
export const SCHEMA = [
  { panel: 'Scale & volume', items: [
    { key: 'studs', label: 'Stud count', type: 'int', min: 4, max: 96, step: 1, help: 'studs on the reference side of the bounding box' },
    { key: 'ref', label: 'Reference side', type: 'select', options: [['min3', 'smallest bbox side'], ['maxh', 'longest horizontal side']] },
    { key: 'mode', label: 'Volume mode (surface orientation: keeps air between wings; NOT a hollow interior, see Hollow core)', type: 'select', options: [['hollow', 'hollow (surface orientation)'], ['envelope', 'envelope (lowest..highest hit)']],
      help: 'hollow keeps the air between wings / under bellies; open meshes fall back to the envelope per column' },
    { key: 'snap', label: 'Ground snap (LDU)', type: 'num', min: 0, max: 48, step: 1 },
    { key: 'minGap', label: 'Min air gap (LDU)', type: 'num', min: 0, max: 24, step: 0.5, help: 'thinner air between two solids is closed' },
    { key: 'minThick', label: 'Fatten thin sheets to 1 plate', type: 'bool' },
    { key: 'superSample', label: 'Volume supersampling', type: 'int', min: 1, max: 3, step: 1, help: 'rays per field cell per axis (n x n, area average). 1 point-samples the cell centre; 2 is ~4x the cast cost and more exact, but the coverage thresholds are tuned for point sampling' },
    { key: 'fieldSmooth', label: 'Smooth thin features', type: 'num', min: 0, max: 0.5, step: 0.05, help: 'blend a cell with its lateral neighbours where the neighbourhood is sparse, so a strut thinner than a cell stops wandering between cells. Helps strut-heavy models (aircraft), costs fidelity on dense ones' },
    { key: 'surfaceSamples', label: 'Surface samples', type: 'int', min: 20000, max: 800000, step: 10000, help: 'colour + thin-feature detection' },
    { key: 'seed', label: 'Random seed', type: 'int', min: 0, max: 9999, step: 1 },
  ] },
  { panel: 'Grid phase & symmetry', items: [
    { key: 'offsets', label: 'Grid offsets tried (LDU)', type: 'multi', options: [0, 4, 8, 12, 16], help: 'tried on both axes (only on the free axis for symmetric models)' },
    { key: 'symmetry', label: 'Mirror symmetry', type: 'select', options: [['auto', 'auto-detect'], ['off', 'off']] },
    { key: 'symThreshold', label: 'Symmetry threshold', type: 'num', min: 0.001, max: 0.03, step: 0.0005, help: 'mean mirror distance / bbox diagonal' },
    { key: 'parity', label: 'Width parity', type: 'select', options: [['auto', 'auto (solve both)'], ['even', 'even: plane on a stud seam'], ['odd', 'odd: plane on a stud centre line']] },
  ] },
  { panel: 'Part selection phases', items: [
    { key: 'motifs', label: 'M motifs: assemblies mined from official sets (broad phase)', type: 'bool', help: 'multi-part assemblies seen repeatedly in the OMR models (docs/omr) are tried first, as one candidate each; the single-part phases then fill what is left. See docs/MOTIFS.md' }, { key: 'motifTol', type: 'tol', when: 'motifs' },
    { key: 'motifMinModels', label: 'motif: min source models', type: 'int', min: 1, max: 50, step: 1, when: 'motifs', help: 'an assembly must occur in at least this many different official sets' },
    { key: 'motifMaxParts', label: 'motif: max parts', type: 'int', min: 2, max: 24, step: 1, when: 'motifs' },
    { key: 'motifShapedOnly', label: 'motif: only assemblies with a shaped part', type: 'bool', when: 'motifs', help: 'off = also brick / plate-only arrangements (L-shapes, steps); they tend to take the skin before the slope phase' },
    { key: 'motifMirror', label: 'motif: also the mirror image of each assembly', type: 'bool', when: 'motifs' },
    { key: 'motifSnot', label: 'motif: keep sideways (SNOT) assemblies', type: 'bool', when: 'motifs', help: 'assemblies that hang a part on the side studs of a headlight brick or a bracket; placed as one rigid unit and never re-cut by the merge passes' },
    { key: 'motifStretch', label: 'motif: synthesise the missing lengths of repeating assemblies', type: 'bool', when: 'motifs', help: 'a row of 3 cheese slopes mined from a set also gives the rows of 2, 4, 5 ... that no set happened to contain' },
    { key: 'motifStretchMax', label: 'motif: max repeats', type: 'int', min: 2, max: 16, step: 1, when: 'motifStretch' },
    { key: 'motifSolid', label: 'motif: keep solid boxes (pure brick / plate stacks)', type: 'bool', when: 'motifs' },
    { key: 'motifBonusLog', label: 'motif: score bonus per log2(models)', type: 'num', min: 0, max: 1, step: 0.05, when: 'motifs' },
    { key: 'rounds', label: 'A0 round parts (poles, cones)', type: 'bool' }, { key: 'roundTol', type: 'tol', when: 'rounds' },
    { key: 'skin', label: 'A skin (slopes, curved, cheese, tiles)', type: 'bool' }, { key: 'skinTol', type: 'tol', when: 'skin' },
    { key: 'inverted', label: 'Inverted slopes (undersides)', type: 'bool' },
    { key: 'fillTol', label: 'B fill (bricks / plates)', type: 'tol' },
    { key: 'fill2', label: 'B2 relaxed bricks', type: 'bool' }, { key: 'fill2Tol', type: 'tol', when: 'fill2' },
    { key: 'relaxed', label: 'C relaxed plates / tiles', type: 'bool' }, { key: 'relaxedTol', type: 'tol', when: 'relaxed' },
    { key: 'fallback', label: 'D 1x1 fallback', type: 'bool' }, { key: 'fallbackMin', label: 'fallback min fill', type: 'num', min: 0.1, max: 1, step: 0.05, when: 'fallback' },
    { key: 'thin', label: 'E thin features', type: 'bool' },
    { key: 'thinBand', label: 'thin band (leftover fill)', type: 'range', min: 0, max: 1, step: 0.05, when: 'thin' },
    { key: 'thinPoints', label: 'thin: min surface points / cell', type: 'int', min: 0, max: 50, step: 1, when: 'thin' },
    { key: 'technic', label: 'Technic bricks (instead of bricks)', type: 'bool' },
    { key: 'partSet', label: 'Part set', type: 'select', options: [['limited', 'limited (core set)'], ['extended', 'extended (+ extra LDraw shapes: slopes, wedges, corners, more sizes)']], help: 'extended adds many more shapes; the solver evaluates each one at every cell, so it is slower' },
    { key: 'shapeParts', label: 'Shape parts (arches, panels, dishes, corner tiles, curved tops)', type: 'bool', help: 'frequent LDraw shapes measured as a per-level occupancy rather than a height field, so an arch keeps its opening; added to whichever part set is selected' },
    { key: 'wErr', label: 'Default error weight', type: 'num', min: 0, max: 6, step: 0.1 },
    { key: 'tileExposure', label: 'Tile: max fill above', type: 'num', min: 0, max: 1, step: 0.05 },
  ] },
  { panel: 'Merges & connectivity', items: [
    { key: 'mergeVertical', label: '3 plates -> brick', type: 'bool' },
    { key: 'mergeHorizontal', label: 'Re-pack plates / tiles', type: 'bool' },
    { key: 'colorTol', label: 'Merge colour tolerance', type: 'int', min: 0, max: 255, step: 1 },
    { key: 'pillars', label: 'Columns -> round bricks', type: 'bool' }, { key: 'pillarMinLevels', label: 'min column height (plates)', type: 'int', min: 2, max: 30, step: 1, when: 'pillars' },
    { key: 'pillarCluster', label: 'thin neighbours allowed', type: 'int', min: 0, max: 8, step: 1, when: 'pillars', help: '0 = only a fully isolated column becomes a pole (one stray neighbour used to reject the whole stack); 2 also converts strut pairs and rows. A wider neighbour always vetoes, so a column inside a wall stays a wall' },
    { key: 'vertexNormals', label: 'Fix flipped faces (three.js vertex normals)', type: 'bool', help: 'welds the mesh, lets three.js compute vertex normals and flips every triangle whose winding disagrees with them, before the ray cast reads facing' },
    { key: 'beatFlat', label: 'Shaped parts must beat flat', type: 'num', min: 0.3, max: 1, step: 0.05, help: 'a slope / curve / round / wedge is only placed where its error is below this fraction of the best flat plate-or-brick stack in the same box; 1 = off (floods the skin with 1x1 curved parts)' },
    { key: 'crust', label: 'Hollow core: solve only the crust', type: 'bool', help: 'erases every voxel deeper than the crust depth below the surface before solving: far fewer cells to process on solid / blocky models (trono: 40% of the volume gone, 2x faster)' },
    { key: 'crustDepth', label: 'crust depth (LDU)', type: 'num', min: 20, max: 160, step: 10, when: 'crust', help: '20 = one stud, 40 = two studs (default), 60 = three studs of wall' },
    { key: 'decimate', label: 'Decimate floaters: drop tiny debris specks', type: 'bool', help: 'labels the 3D islands of the volume and erases the tiny ones (debris, stray non-manifold specks) before solving; independent of joining islands below' },
    { key: 'islandDrop', label: 'drop islands smaller than (fraction of the biggest)', type: 'num', min: 0, max: 0.05, step: 0.001, when: 'decimate' },
    { key: 'islandDropMax', label: 'only if smaller than (voxels)', type: 'int', min: 0, max: 2000, step: 5, when: 'decimate' },
    { key: 'islands', label: 'Islands: MST of thin tubes in the source volume', type: 'bool', help: 'joins what survives decimation along a minimum spanning tree with a 1-voxel (4 LDU) tube before solving' },
    { key: 'tubeWidth', label: 'tube width (LDU)', type: 'num', min: 2, max: 16, step: 2, when: 'islands', help: '2-6 = one voxel, 8+ = dilated' },
    //__old label: 'Islands: MST of thin tubes in the source volume', type: 'bool', help: 'labels the 3D islands of the volume, joins them along a minimum spanning tree with a 1-voxel (4 LDU) tube before solving; tiny floaters are removed' },
    { key: 'retile', label: 'Re-tile plate stacks -> bricks', type: 'bool', help: 'three levels of plates of any footprints -> bricks, re-cutting the plates that lose cells; each brick is kept only if the piece count drops and connectivity holds' },
    { key: 'bracing', label: 'Bracing / thickening', type: 'bool' },
    { key: 'braceMaxGap', label: 'max padding (plates)', type: 'int', min: 0, max: 8, step: 1, when: 'bracing' },
    { key: 'braceMaxSpan', label: 'max span (studs)', type: 'int', min: 2, max: 4, step: 1, when: 'bracing' },
    { key: 'braceRounds', label: 'rounds', type: 'int', min: 1, max: 100, step: 1, when: 'bracing' },
    { key: 'splice', label: 'Splice: re-cut touching pieces so a plate spans the seam', type: 'bool', help: 'side-by-side pieces of different components are re-cut into plates (volume unchanged)' },
    { key: 'spliceTime', label: 'splice time budget (ms)', type: 'int', min: 500, max: 60000, step: 500, when: 'splice' },
    { key: 'bridge', label: 'Bridge: shortest plate chain between components', type: 'bool', help: 'Dijkstra through free cells with 1xk plates (zig-zag), stops at the first stud contact' },
    { key: 'bridgeMax', label: 'bridge max plates', type: 'int', min: 1, max: 40, step: 1, when: 'bridge' },
    { key: 'supports', label: 'Support columns (centre of mass)', type: 'bool' },
    { key: 'groundSupports', label: 'columns may stand on the ground', type: 'bool', when: 'supports' },
    { key: 'supportMinFrac', label: 'min component mass', type: 'num', min: 0, max: 0.2, step: 0.005, when: 'supports' },
    { key: 'supportSpacing', label: 'studs per column (long parts)', type: 'int', min: 4, max: 80, step: 1, when: 'supports' },
    { key: 'finish', label: 'Studs finish: flat tiles on top (optional)', type: 'bool', help: 'exposed plates become tiles, exposed bricks get a tile on top. Off by default' },
    { key: 'finishBricks', label: 'exposed bricks', type: 'select', options: [['add', 'add a tile on top'], ['none', 'leave studs']], when: 'finish' },
  ] },
  { panel: 'Colour', items: [
    { key: 'palette', label: 'Colours', type: 'select', options: [['cheat', 'cheat colour (mean of the mesh)'], ['lego', 'snap to LEGO solid palette']] },
    { key: 'colorVisible', label: 'Colour from visible surfaces only', type: 'bool', help: 'ignores surface samples hidden inside the model (ice cream under a glass wall) so they cannot bleed through the skin' },
    { key: 'colorK', label: 'Samples per piece', type: 'int', min: 1, max: 64, step: 1 },
  ] },
];

export const TOL_FIELDS = [['min_cov', 'min coverage', 0, 1, 0.01], ['max_err', 'max error', 0, 1, 0.01], ['piece_pen', 'piece penalty', 0, 3, 0.05], ['w_err', 'error weight', 0, 6, 0.1]];
